platform :ios, '9.0'
use_frameworks!

target 'UCSiding_Example' do
    pod 'UCSiding', path: '../'
    
    target 'UCSiding_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.8'
        pod 'Nimble', '~> 3.0'
    end
end
