platform :ios, '9.0'
use_frameworks!

target 'UCSiding_Example' do
    pod 'UCSiding', path: '../'
    
    target 'UCSiding_Tests' do
        inherit! :search_paths
        
#        pod 'Quick', '~> 0.9'
#        pod 'Nimble', '~> 4.1.0'
        pod 'Alamofire', '~> 4.0.0'
        pod 'Kanna', '~> 1.1.1'
    end
end
